# Generated by Django 3.2.2 on 2021-05-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_num', models.IntegerField(default=0)),
                ('pool_m_won', models.IntegerField(default=0)),
                ('pool_m_lost', models.IntegerField(default=0)),
                ('pool_m_tied', models.IntegerField(default=0)),
                ('pool_r_won', models.IntegerField(default=0)),
                ('pool_r_lost', models.IntegerField(default=0)),
                ('pool_r_rate', models.IntegerField(default=0)),
                ('pool_K1', models.IntegerField(default=0)),
                ('pool_A1', models.IntegerField(default=0)),
                ('pool_D1', models.IntegerField(default=0)),
                ('pool_KD1', models.IntegerField(default=0)),
                ('pool_K2', models.IntegerField(default=0)),
                ('pool_A2', models.IntegerField(default=0)),
                ('pool_D2', models.IntegerField(default=0)),
                ('pool_KD2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_map', models.CharField(max_length=32)),
                ('match_date', models.DateTimeField(unique=True)),
                ('match_duration', models.TimeField()),
                ('match_waiting', models.TimeField()),
                ('match_r_won', models.IntegerField()),
                ('match_r_lost', models.IntegerField()),
                ('match_K1', models.IntegerField()),
                ('match_A1', models.IntegerField()),
                ('match_D1', models.IntegerField()),
                ('match_MVP1', models.IntegerField()),
                ('match_HSP1', models.IntegerField()),
                ('match_score1', models.IntegerField()),
                ('match_K2', models.IntegerField()),
                ('match_A2', models.IntegerField()),
                ('match_D2', models.IntegerField()),
                ('match_MVP2', models.IntegerField()),
                ('match_HSP2', models.IntegerField()),
                ('match_score2', models.IntegerField()),
                ('match_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pools')),
            ],
        ),
    ]
