# Generated by Django 3.2.2 on 2021-05-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210527_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='pools',
            name='pool_HSP1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pools',
            name='pool_HSP2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pools',
            name='pool_MVP1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pools',
            name='pool_MVP2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pools',
            name='pool_pts1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pools',
            name='pool_pts2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pools',
            name='pool_ptsadd1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pools',
            name='pool_ptsadd2',
            field=models.IntegerField(default=0),
        ),
    ]
