# Generated by Django 3.2.2 on 2021-05-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210528_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='match_duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='matches',
            name='match_waiting',
            field=models.DurationField(),
        ),
    ]
