# Generated by Django 3.2.2 on 2021-05-31 21:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210528_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='pools',
            name='pool_skipped',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='default', max_length=16), default='defaults', size=None),
            preserve_default=False,
        ),
    ]
