# Generated by Django 3.2.2 on 2021-05-31 21:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_pools_pool_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pools',
            name='pool_skipped',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None),
        ),
    ]
