# Generated by Django 3.2.2 on 2021-05-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_pools_pool_skipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pools',
            name='pool_skipped',
        ),
        migrations.AddField(
            model_name='pools',
            name='pool_skipped1',
            field=models.CharField(default='default', max_length=16),
        ),
        migrations.AddField(
            model_name='pools',
            name='pool_skipped2',
            field=models.CharField(default='default', max_length=16),
        ),
    ]
