# Generated by Django 3.2.2 on 2021-05-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210531_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pools',
            name='pool_skipped1',
        ),
        migrations.RemoveField(
            model_name='pools',
            name='pool_skipped2',
        ),
        migrations.AddField(
            model_name='pools',
            name='pool_skipped',
            field=models.CharField(default='default', max_length=128),
        ),
    ]
