# Generated by Django 3.2.2 on 2021-06-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210531_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pools',
            name='pool_skipped',
            field=models.CharField(default='Nothing skipped yet', max_length=128),
        ),
    ]
