# Generated by Django 3.2.2 on 2021-06-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_pools_pool_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pools',
            name='pool_skipped',
            field=models.CharField(default='["Nothing skipped yet"]', max_length=128),
        ),
    ]
