# Generated by Django 3.2.2 on 2021-06-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_pools_pool_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pools',
            name='pool_skipped',
            field=models.CharField(default='Error', max_length=128),
        ),
    ]
